### PR TITLE
support insecure bind

### PR DESCRIPTION
**Pull request by seidnerj**
This is especially useful when developing locally.

### CODE REVIEW

**Comment by pgjones** [comment]
This isn't required, without the ssl certs it will default to an insecure bind (as does Hypercorn). The insecure bind option exists in Hypercorn to allow secure and insecure binds at the same time.

**Comment by seidnerj** [comment]
Please reopen this, this was my intent. I need both at the same time to locally replicate an issue I'm facing with hypercorn in production.

**Comment by seidnerj** [comment]
Please reopen this, this was my intent. I need both http and https at the same time.

**Comment by pgjones** [comment]
I think this is too niche for the app.run shortcut method. I would run Hypercorn directly (or create your own run command that does this).

**Comment by seidnerj** [comment]
There are ways around this for sure, but why not include such an option out of the box? 

If a production environment via hypercorn allows this, then why shouldn't a development environment allow easily replicating this?

**Comment by pgjones** [comment]
The app.run is meant to be a simple development default i.e. few options. It isn't much effort to run hypercorn directly or create a custom run function.

**Comment by seidnerj** [comment]
I find there's a lot of value in having this as it simplifies setting up the dev environment that's identical to the prod one, moreover - it think it is not intuitive that this is missing, that's the first place I looked to enable this, but obviously it is up to you...

**Pull request closed without merging**
